#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🔍 Preparing to commit: Running code analysis and build process...'

# Check code formatting using Prettier
npm run check-format ||
(
    echo '🔴 Prettier Check Failed: Your code styling does not meet the standards.
          Please run "npm run format", add the changes, and then reattempt the commit.';
    false;
)

# Check code quality using ESLint
npm run check-lint ||
(
    echo '🔴 ESLint Check Failed: Your code contains quality issues that need to be addressed.
          Review the listed problems, make the necessary changes, and try committing again.'
        false; 
)

# Validate TypeScript type correctness
npm run check-types ||
(
    echo '🔴 Type Check Failed: There are issues with the TypeScript type correctness.
          Please resolve the indicated problems before proceeding.'
    false;
)

# If all checks pass, proceed to build
echo '🛠️ Building the project...'

npm run build ||
(
    echo '🔴 Build Failed: The project failed to build properly.
          Examine the error messages above for insights into the issues.'
    false;
)

# If all checks and build pass, proceed to commit
echo '✅ All checks passed. Committing changes...'
